CREATE TABLE "USER_DATA" (
    "ID" VARCHAR(36) NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "LOGIN" VARCHAR NOT NULL UNIQUE,
    "PASSWORD" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    "IS_APPROVAL" BOOLEAN NOT NULL
);