CREATE TABLE "USER_DATA" (
    "ID" BIGINT NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "LOGIN" VARCHAR NOT NULL UNIQUE,
    "PASSWORD" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL
);

CREATE TABLE "MESSAGE_STATE" (
    "ID" VARCHAR(36) NOT NULL PRIMARY KEY,
    "REQUEST_MESSAGE" VARCHAR NOT NULL,
    "RESPONSE_MESSAGE" VARCHAR
);