CREATE TABLE "USER_DATA" (
    "ID" VARCHAR(36) NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "LOGIN" VARCHAR NOT NULL UNIQUE,
    "PASSWORD" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    "IS_APPROVAL" BOOLEAN NOT NULL
);

CREATE TABLE "MESSAGE_STATE" (
    "ID" VARCHAR(36) NOT NULL PRIMARY KEY,
    "CORRELATION_ID" VARCHAR(36) NOT NULL,
    "QUEUE_NAME" VARCHAR NOT NULL,
    "PROPERTY_BODY_NAME" VARCHAR NOT NULL
)